# -*- coding: utf-8 -*-
"""spam_email.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19_A2YjtVEWDObWejFKmFU5It36F6_M9F
"""

import kagglehub
path = kagglehub.dataset_download("ashfakyeafi/spam-email-classification")

import pandas as pd
import os

csv_files = [f for f in os.listdir(path) if f.endswith('.csv')]

if csv_files:
    data_file_path = os.path.join(path, csv_files[0])
    df = pd.read_csv(data_file_path)
    print("Dataset loaded successfully. Here's the head of the DataFrame:")
    print(df.head())



# Download necessary NLTK data
import nltk
nltk.download('stopwords')
nltk.download('wordnet')

import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import string

# Initialize lemmatizer and stopwords
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    # Convert to lowercase
    text = text.lower()
    # Remove punctuation
    text = ''.join([char for char in text if char not in string.punctuation])
    # Remove numbers
    text = re.sub(r'\d+', '', text)
    # Tokenize and remove stopwords, then lemmatize
    tokens = text.split()
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
    return ' '.join(tokens)

# Apply preprocessing to the 'Message' column
df['Preprocessed_Message'] = df['Message'].apply(preprocess_text)

print("Original Message vs. Preprocessed Message:")
for i in range(5):
    print(f"Original: {df['Message'].iloc[i]}")
    print(f"Preprocessed: {df['Preprocessed_Message'].iloc[i]}\n")

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# Initialize TF-IDF Vectorizer
tfidf_vectorizer = TfidfVectorizer(max_features=5000)

# Fit and transform the preprocessed messages
X = tfidf_vectorizer.fit_transform(df['Preprocessed_Message'])

# Encode the target variable 'Category'
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(df['Category'])

print("Shape of TF-IDF features (X):", X.shape)
print("Shape of encoded labels (y):", y.shape)
print("Original categories:", label_encoder.classes_)
print("Encoded labels (first 5):\n", y[:5])

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

from sklearn.ensemble import RandomForestClassifier

# Initialize the Random Forest Classifier
random_forest_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
random_forest_model.fit(X_train, y_train)

print("Random Forest Classifier trained successfully!")

from sklearn.metrics import classification_report, accuracy_score

# Make predictions on the test set
y_pred = random_forest_model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print("Classification Report:")
print(report)

# Save the trained model and vectorizer to files
import pickle
with open('spam_email.pkl', 'wb') as model_file:
    pickle.dump(random_forest_model, model_file)

with open('spam_vectorizer.pkl', 'wb') as vectorizer_file:
    pickle.dump(tfidf_vectorizer, vectorizer_file)

print("Saved spam_email.pkl and spam_vectorizer.pkl")